image: node:20-alpine

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - dist/

test-job1:
  stage: test
  script:
    - npm install --legacy-peer-deps
    - npm run test --watch=false

test-job2:
  stage: test
  needs:
    - test-job1
  script:
    - echo "Simulating a longer-running test job."
    - sleep 20

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production

pages:
  stage: deploy
  dependencies:
    - build-job
  script:
    - mkdir -p public
    - cp -r dist/habit-tracker-dashboard/browser/* public
  artifacts:
    paths:
      - public
  only:
    - main
