image: node:20-alpine

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - dist/

test-job1:
  stage: test
  script:
    - npm install --legacy-peer-deps  # Added --legacy-peer-deps flag
    - npm run test --watch=false

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

pages:
  stage: deploy
  script:
    - npm install --legacy-peer-deps
    - npm run build
    - rm -rf public
    - mkdir -p public
    - cp -r dist/habit-tracker-dashboard/browser/* public/
  artifacts:
    paths:
      - public
  only:
    - main
