image: node:20-alpine  # Using Node.js image instead of alpine

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - dist/  # Angular builds to dist directory by default

test-job1:
  stage: test
  script:
    - npm install
    - npm run test --watch=false  # Run tests in CI mode

test-job2:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - sleep 20

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - cp -r dist/*/browser/* public/  # Copy Angular build output to public directory
  artifacts:
    paths:
      - public
  only:
    - main